<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dsa_stattracker_xplat\dsa_stattracker_xplat.csproj" />
  </ItemGroup>
</Project>
